attributes:
  nfs_endpoint:
    value: '/nfs'
    label: 'NFS endpoints (Shared folder on NFS Server)'
    description: 'e.g. /nfs/vol'
    weight: 25
    type: "text"
    regex:
      source: '.+'
      error: "This field should not be empty"
  nfs_mount_options:
    value: ''
    label: 'NFS mount options'
    description: 'optional NFS mount parameters'
    weight: 25
    type: "text"
  nfs_mount_point:
    value: '/mnt/nfs'
    label: 'Cinder mount point base folder:'
    description: 'e.g. /mnt/nfs'
    weight: 20
    type: 'text'
    regex:
      source: '.+'
      error: "This field should not be empty"
  nfs_net_mask:
    value: '255.255.255.0'
    label: 'NFS Network Mask:'
    description: 'e.g. 255.255.255.0'
    weight: 30
    type: 'text'
    regex:
      source: '.+'
      error: "This field should not be empty"
  nfs_sparsed_volumes:
    type: "checkbox"
    weight: 30
    value: True
    label: "NFS sparsed volumes"
    description: "Create volumes as sparsed files which take no space.If set to False volume is created as regular file."
